'use strict';

const tkValid =
  'tk.eyJ1IjoiZWZmeSIsImV4cCI6MjY5Mzg3NTI0MywiaWF0IjoxNjkzODcxNjQzLCJzY29wZXMiOltdLCJjbGllbnQiOiJtYXBib3guY29tIiwibGwiOjE2OTI2MzM0MDIxMjIsIml1IjpudWxsLCJlbWFpbCI6ImVmZnlAbWFwZm94LmNvbSJ9.signature';

const pkValid =
  'pk.eyJ1IjoiZWZmeSIsImV4cCI6MjY5Mzg3NTI0MywiaWF0IjoxNjkzODcxNjQzLCJzY29wZXMiOltdLCJjbGllbnQiOiJtYXBib3guY29tIiwibGwiOjE2OTI2MzM0MDIxMjIsIml1IjpudWxsLCJlbWFpbCI6ImVmZnlAbWFwZm94LmNvbSJ9.signature';

const skValid =
  'pk.eyJ1IjoiZWZmeSIsImV4cCI6MjY5Mzg3NTI0MywiaWF0IjoxNjkzODcxNjQzLCJzY29wZXMiOltdLCJjbGllbnQiOiJtYXBib3guY29tIiwibGwiOjE2OTI2MzM0MDIxMjIsIml1IjpudWxsLCJlbWFpbCI6ImVmZnlAbWFwZm94LmNvbSJ9.signature';

module.exports = {
  tkValid,
  pkValid,
  skValid
};
