name: Basic Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  nodeVersion: 22

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install npm dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4

      - run: npm install
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run test
